### ISSUE TITLE
Failed to start new version on Linux

### ISSUE THREAD

**Issue by Paval-from-Belarus** [Khmelov/DC2024-01-27#1]
The newest version of compiled jar (I still wonder why) cannot be started via wine (wine 9.1). The program failed with exception: 
```
Unhandled exception: unimplemented function IPHLPAPI.DLL.GetAnycastIpAddressTable called in 64-bit code (0x006fffffc5e6e8).
```
It seems the program uses tricky native function not implemented in wine)

**Comment by demologin** [comment]
I'll have to try to repeat this. In general, this is a java application made on MacOS. It is possible that this is the tricks of GraalVM

**Comment by demologin** [comment]
On the other hand, if I repeat it in Linux, it will be easier for me to just build the application there. In general, I'll come up with something.

**Comment by Paval-from-Belarus** [comment]
Wait with impatience)

**Comment by demologin** [comment]
Последняя версия имеет те же проблемы?

**Comment by Paval-from-Belarus** [comment]
That's amazing the file was compiled for AArch64) But linux can easily run it with qemu. It works! Thanks)

**Comment by Paval-from-Belarus** [comment]
I forgot to mention opening a browser. The program uses `exec http://localhost:24100` to open the browser (exec is used to run executable files, no more). Use instead `xdg-open http://localhost:24100`. This's common approach in most distros to use xdg-utils (except some bare bones' crazy guys))
