### ISSUE TITLE
При создании Editor-а пароль менее 8 символов

### ISSUE THREAD

**Issue by BashlikovV** [Khmelov/DC2024-01-27#11]
![image](https://github.com/Khmelov/DC2024-01-27/assets/90571901/808fd240-b4de-4ae1-b5a3-2ddb688fecc9)
Пароль менее 8 символов, ожидаемый результат 201:
![image](https://github.com/Khmelov/DC2024-01-27/assets/90571901/cd55beb4-b9a4-4361-aca4-057b254c161d)
![image](https://github.com/Khmelov/DC2024-01-27/assets/90571901/388dc871-c707-4f18-84cd-cdfdd4843b8b)
Далее во всех тестах генерятся не правильныe id:
![image](https://github.com/Khmelov/DC2024-01-27/assets/90571901/8fbceeab-e221-4b55-b1d2-ecc43c39c6b9)

**Comment by Khmelov** [comment]
А версия последняя? Я вроде на выходных пофиксил.
