### ISSUE TITLE
Длина атрибута "login" не больше 64 символов

### ISSUE THREAD

**Issue by RBELS** [Khmelov/DC2024-01-27#12]
Task 2
Вариант: Issue, Label, Post, User

Вероятно, подразумевается, что длина передаваемого в тесте значения атрибута "login" больше 64 символов, но по факту его длина 64
![telegram-cloud-photo-size-2-5395717309332575895-y](https://github.com/Khmelov/DC2024-01-27/assets/50217581/969465bc-f82c-4707-82df-fb83ced395f0)

![telegram-cloud-photo-size-2-5395717309332575894-y](https://github.com/Khmelov/DC2024-01-27/assets/50217581/cb239471-02de-44ac-b3dc-a7e65b07781c)

**Comment by Khmelov** [comment]
Перезалил. Теперь 65 символов )))
