### ISSUE TITLE
Ошибка при создании объекта News

### ISSUE THREAD

**Issue by FedorDevelopmer** [Khmelov/DC2024-01-27#14]
В тестах ожидается создание объекта типа News с кодом 201, при этом на вход подается только часть необходимых для создания полей.

![изображение_2024-02-28_192423647](https://github.com/Khmelov/DC2024-01-27/assets/91414600/23f3f825-f20c-4547-b232-2f7a1d16090c)

При этом поле name в целом отсутствует для News.

![image](https://github.com/Khmelov/DC2024-01-27/assets/91414600/40a262fe-31b0-4128-8a41-08e02fd1ecde)

**Comment by Khmelov** [comment]
Спс. Name исправлю - это баг. А про времена спорно - довольно логично же, что когда их нет есть еще две точки где можно их поставить (на сервере и в базе). Юзер пишет пост на хабре твиттере медиуме - нигде же у него нет возможности управлять датами, верно? Тут наверное нужно мне задание мне уточнить.
