### ISSUE TITLE
New tests bug

### ISSUE THREAD

**Issue by NomedXD** [Khmelov/DC2024-01-27#198]
После обновления тестов и добавления в раздел JPA новых "стучаний" в базу данных, получаем вот такую штуку: 
![image](https://github.com/Khmelov/DC2024-01-27/assets/90419311/b56888d5-03a6-451e-b0e9-100b30fbd6a6)
Пароль сервера postgres, user тоже postgres, соответственно в properties:
spring.datasource.username=postgres
spring.datasource.password=postgres
Насколько я понял, эти тесты пытаются вообще без пароля постучаться, потому что если сделать assign data source через IDEA с указанным в ошибке URL: jdbc:postgresql://127.0.0.1/distcomp, то будет как раз такая же ошибка как на скрине. Но если поставить пароль postgres, то data source установится.
Без этих новых запросов все тесты проходили :)

**Comment by Khmelov** [comment]
Занятно. База на которой тестирую вроде бы postgres+postgres. Через часок посмотрю.

**Comment by Khmelov** [comment]
<img width="1806" alt="image" src="https://github.com/Khmelov/DC2024-01-27/assets/17061547/2ea5fe9a-ca99-4e4e-9ce2-6d0c6621176d">
То на чем проверял такое как надо вроде. Но код пока глянуть не могу.

**Comment by Khmelov** [comment]
Нашел багу, действительно, без пароля создается соединение, чтение было из ресурсов, они в JVM ок, а в graal-сборку не попадают. Сделаю фикс через час где-то.

**Comment by Khmelov** [comment]
Перезалил. Помогло?

**Comment by NomedXD** [comment]
> Перезалил. Помогло?

Все, работает, спасибо 👍  А что за новые модные файлы добавились, под фикс этого бага?)

**Comment by Khmelov** [comment]
Это либы для винды и PG. На случай если их нет на хосте.

**Comment by Khmelov** [comment]
По идее и без них должно заводиться, перестраховался.
