### ISSUE TITLE
Возможные ошибки в тестах

### ISSUE THREAD

**Issue by Ringo2901** [Khmelov/DC2024-01-27#2]
![изображение_2024-02-19_233311747](https://github.com/Khmelov/DC2024-01-27/assets/92538968/0b803e0e-9ef8-46f4-8c39-d7a71cbf6d96)
В данном случае обновление должно происходить успешно, т.к. при post запросе создался editor с id = 6, как и в request у запроса на обновление.

![image](https://github.com/Khmelov/DC2024-01-27/assets/92538968/c4b1e16c-05c5-4bfd-a825-c526d5ee5bce)
Значения editorId вроде бы совпадают, но ошибка осталась.

Если я что-то недопонял, сори, жду комментарии)

**Comment by demologin** [comment]
Все возможно, написал тупо "в лоб". Надо повторить проблему. Есть репо?

**Comment by demologin** [comment]
в 10 надо проверить что в json число а не строка

**Comment by Ringo2901** [comment]
А валидацию по поводу длины логина мы берем из данных в этой таблице, что там текст длиной от 2 до 64?
![image](https://github.com/Khmelov/DC2024-01-27/assets/92538968/0452494d-6ce6-42bf-8e1f-089d0febf52c)

**Comment by demologin** [comment]
ну да. если длина логина 1 то должно падать

**Comment by demologin** [comment]
я в этом наборе только логин проверяю, на следующей пачке проверок будет больше. лучше сразу сделать как надо.

**Comment by Ringo2901** [comment]
Да, судя по всему у меня в json response editorId как строка лежит, поэтому не проходит
![image](https://github.com/Khmelov/DC2024-01-27/assets/92538968/0c44c85e-3590-4e74-aa38-a84385e16118)

**Comment by demologin** [comment]
Да. Там только один вариант прокатывает. Детализацию писать понятное дело лень ))))
