### ISSUE TITLE
Поменялся вариант после последнего обновления.

### ISSUE THREAD

**Issue by TishalovichMaxim** [Khmelov/DC2024-01-27#20]
В новой версии задания (26.02.2024) вариант содержит схему с Author, News, Comment, Tag. В прошлых версиях (24.02.2024 и раньше) был вариант с Author, Story, Message, Label.

Вводимый email: tishalovichm@gmail.com

**Comment by Khmelov** [comment]
На всех заданиях такое?

**Comment by Khmelov** [comment]
Занятно. Не воспроизводится. 
На самой первой версии запустил с этой почтой: Author, News, Comment, Tag
Вечером дома посмотрю внимательно.

**Comment by Khmelov** [comment]
Надо чтобы у всех без исключения такое повторилось, и тогда баг у меня. Если же это одиночный кейс, значит была ошибка при вводе почты.

**Comment by NomedXD** [comment]
У меня тоже такое было, но после пары переустановок и нескольких повторных запусков все вернулось

**Comment by Khmelov** [comment]
Она ищет файл config.properties и там должен быть
email=tishalovichm@gmail.com

Придется похоже логирование прилепить. Так не поймать....

**Comment by NomedXD** [comment]
> Ага. Вот что возможно..... Если удалить файл конфига, ввести почту, войти то при первом запуске будет такой набор Author, News, Comment, Tag а при втором и последующих Author, Story, Message, Label. Это что-то с сохранением свойств похоже я намудрил. Ндо в коде смотреть. Так не увижу.

Возможно, я когда обновляю версию, сношу и properies файл. Значит действительно это и ломается, похоже, стоит его просто оставлять, а обновлять только сам exe-шник

**Comment by Khmelov** [comment]
> > Ага. Вот что возможно..... Если удалить файл конфига, ввести почту, войти то при первом запуске будет такой набор Author, News, Comment, Tag а при втором и последующих Author, Story, Message, Label. Это что-то с сохранением свойств похоже я намудрил. Ндо в коде смотреть. Так не увижу.
> 
> Возможно, я когда обновляю версию, сношу и properies файл. Значит действительно это и ломается, похоже, стоит его просто оставлять, а обновлять только сам exe-шник

Да, так будет ок. Но мне все равно это надо подфиксить, насколько помню там бин контекста с вариантом финализированный и поэтому он обновляется только после перезапуска.
