### ISSUE TITLE
Ошибочный путь запроса в тесте

### ISSUE THREAD

**Issue by NomedXD** [Khmelov/DC2024-01-27#21]
Здесь, судя по всему, проверяется, чтобы Message не создался с несуществующим tweetId, но POST летит на POST http://localhost:24110/api/v1.0/tweets, а должно на POST http://localhost:24110/api/v1.0/messages
![image](https://github.com/Khmelov/DC2024-01-27/assets/90419311/8e04df27-1027-4cbb-964d-199277007bc8)

**Comment by Khmelov** [comment]
Маловато данных. Нужен email и номер работы.
