### ISSUE TITLE
Editor - Tweet - Tag - Note Test 7 bug

### ISSUE THREAD

**Issue by V-O-N-hope** [Khmelov/DC2024-01-27#22]
![image](https://github.com/Khmelov/DC2024-01-27/assets/83778394/ef74d3e3-4aef-4139-92aa-23bdb75f5e53)

При выполнение теста идет запрос на обновление элемента, причем id передается тоже что и вернул сервер, т.е. элемент с таким id сущетсвует Во время выполнения теста хранится только одна сущность и получается что значения полей могут быть любыми.

Приходят такие данные 
![image](https://github.com/Khmelov/DC2024-01-27/assets/83778394/5bae4bc0-5995-475a-804a-162ab711c4ec)

Репозиторий хранит такую сущность 
![image](https://github.com/Khmelov/DC2024-01-27/assets/83778394/91a5e9b0-96a1-4d8a-b9ed-70e89b21443b)

**Comment by Khmelov** [comment]
Там логин 1 символ. Он не валидный. Поэтому ожидается отказ в update. Остальные поля роли уже не играют. Даже id

**Comment by V-O-N-hope** [comment]
Понял, спасибо
