### ISSUE TITLE
Вопрос по 3 лабораторной

### ISSUE THREAD

**Issue by NomedXD** [Khmelov/DC2024-01-27#26]
Правильно ли, что: 
1) Если мне нужно выделить в отдельный модуль Messages, то запросы на создание сущности message должны все еще прилетать на старый контроллер из модуля publicator
2) Через какой-то дополнительный внутренний сервис publicator мы, используя RestTemplate и нужный URI, посылаем запрос на создание message контроллеру микросервиса discussion
3) Он создает эту сущность и возвращает ResponseEntity, который и вернется в итоговом ответе

**Comment by Khmelov** [comment]
1 2 3 -  все верно
