### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by Katletos** [Khmelov/DC2024-01-27#3]
Why password is not fixed size string? We must hash such sensitive data.
![image](https://github.com/Khmelov/DC2024-01-27/assets/40485432/228f4ff7-95be-4f23-9d8a-64fcf968bad4)

**Comment by Khmelov** [comment]
There are no problems inside the database, of course it makes sense to both salt and encrypt. The task concerns input validation. The following tests will not check this data against the database - any solution will be considered correct.

**Comment by Khmelov** [comment]
Light way https://docs.spring.io/spring-security/reference/features/authentication/password-storage.html#authentication-password-storage
