### ISSUE TITLE
Вопрос по тесту через драйвер в 3 лабе

### ISSUE THREAD

**Issue by Ringo2901** [Khmelov/DC2024-01-27#55]
Здравствуйте, в одном из тестов в 3 лабе вы проверяете кассандру через драйвер, однако у меня тест скипается
![image](https://github.com/Khmelov/DC2024-01-27/assets/92538968/296b4a17-4530-45d7-ab45-c703d91aacd6)

У себя смотрю, что key_space, название таблицы, порт, все сходится и сам запрос у меня работает. Может можно как-то по-другому протестить, если ошибка у меня?

![image](https://github.com/Khmelov/DC2024-01-27/assets/92538968/fa521666-bfc7-485a-b197-a67d3938b95e)
![image](https://github.com/Khmelov/DC2024-01-27/assets/92538968/5fe96e3f-47b8-49b4-a4e4-32cbfaee4b9a)
![image](https://github.com/Khmelov/DC2024-01-27/assets/92538968/998a8283-e614-49a2-846a-cdc2fc536531)

**Comment by Khmelov** [comment]
Там же в логе написано почему пропущено. Я через драйвер не сделал еще ))))

**Comment by Khmelov** [comment]
Тест если зеленый - значит все ок.

**Comment by Ringo2901** [comment]
Просто подумал, что это ко мне относится 🤣

**Comment by Khmelov** [comment]
Не, это ко мне относится ))))
