### ISSUE TITLE
Проверка решения в последней версии dc-preview не работает

### ISSUE THREAD

**Issue by Demian23** [Khmelov/DC2024-01-27#60]
Для версии на **Macos**, для обоих исполняемых файлов, в разделах **REST** и **JPA**. GET /test/310 идёт, затем ничего. В старой версии работает.

**Comment by Khmelov** [comment]
Вот как. По идее такое на всех версиях должно тогда быть.... Я посмотрю. А это тот вариант где уже Kafka есть?

**Comment by Khmelov** [comment]
Пересобрал. Должно быть нормально.
