### ISSUE TITLE
Не могу поменять аккаунт, чтобы вернуть задание, которое было изначально.

### ISSUE THREAD

**Issue by Andrik7289** [Khmelov/DC2024-01-27#63]
При перезапуске dc-preview я ввел случайно неправильный аккаунт, теперь у меня другие задания, а я сделал уже по тому, что было изначально. Файл config.properties у меня не создается и я не могу поменять там аккаунт. Помогите плиз)

**Comment by Khmelov** [comment]
Надо закрыть приложение и вкладки + почистить куки на localhost (я тут перенес конфиг). Спросит заново.

**Comment by Khmelov** [comment]
Надо бы наверное кнопочку для этого приделать. Подумаю....

**Comment by Andrik7289** [comment]
Спасибо)
