### ISSUE TITLE
Неправильно приходит JSON в /api/v1.0/storys POST

### ISSUE THREAD

**Issue by VeceluXa** [Khmelov/DC2024-01-27#68]
Во всех тестах Story создается со следующим Body:
![image](https://github.com/Khmelov/DC2024-01-27/assets/62480297/7f312551-9a33-4bfb-8144-82908035dae2)

Однако в одном из тестов JSON отличается (content меняется на name)
![image](https://github.com/Khmelov/DC2024-01-27/assets/62480297/de5383ea-1366-43ba-a01a-76ff67ae5792)

**Comment by VeceluXa** [comment]
![image](https://github.com/Khmelov/DC2024-01-27/assets/62480297/50282648-8c6e-4638-aaa3-72a1be71f358)

Также я смотрел по логам мне не приходит один из запросов (CHECK REST Sticker 32. After All (Delete User + Story)). В дебаг консоли есть запрос до него, а также запрос после него. В предыдущих тестах этот запрос успешно вызывался и отрабатывал.

**Comment by VeceluXa** [comment]
Также в POST api/v1.0/storys приходит запрос с api/v1.0/posts
![image](https://github.com/Khmelov/DC2024-01-27/assets/62480297/5958f70b-338b-4309-9eb4-a85dfb699e74)

**Comment by demologin** [comment]
Я это помнится вроде как фиксил уже. 
Версия перезаливается каждую неделю, она последняя ??

**Comment by Khmelov** [comment]
Я это помнится вроде как фиксил уже.
Версия перезаливается каждую неделю, она последняя ??

**Comment by Khmelov** [comment]
Вот тут было такое https://github.com/Khmelov/DC2024-01-27/issues/13

**Comment by VeceluXa** [comment]
Да, у меня была не самая свежая версия, извиняюсь.
