### ISSUE TITLE
Поле storyId в сущности Label.

### ISSUE THREAD

**Issue by TishalovichMaxim** [Khmelov/DC2024-01-27#7]
На схеме приложения связь между Story и Label many to many, а при создании Label указывается __storyId__. Также в техническом задании данное поле при создании сущности Label не указывается.

## Операция Create Label:

![image](https://github.com/Khmelov/DC2024-01-27/assets/108403999/fd0e170e-3ef4-43d1-b695-4ad1e1a0c99c)

## Входные/выходные данные теста

![image](https://github.com/Khmelov/DC2024-01-27/assets/108403999/2513520c-33ee-4f74-9a29-ac10b3abf840)

## Схема приложения

![image](https://github.com/Khmelov/DC2024-01-27/assets/108403999/f8f7d14e-7ab9-49c2-afee-17a592070892)

**Comment by demologin** [comment]
Посмотрю, это точно ошибка (в коде тестов скорее всего).

**Comment by Khmelov** [comment]
Посмотрю, это точно ошибка

**Comment by Khmelov** [comment]
Да, точно. Сделал фикс, но обновлю или завтра вечером или в пн скорее всего
