### ISSUE TITLE
При создании автора иногда длина пароля равняется 7, а ожидается 201 Created.

### ISSUE THREAD

**Issue by TishalovichMaxim** [Khmelov/DC2024-01-27#8]
Иногда пароль состоит из 7 символов, а на схеме минимально 8. При этом ожидается 201 Created.

![image](https://github.com/Khmelov/DC2024-01-27/assets/108403999/463c32b3-809c-4838-bbac-728cf2e1c8f9)

![image](https://github.com/Khmelov/DC2024-01-27/assets/108403999/d054b4b3-9bef-4e50-8fd5-00c1491ada63)

## Сущность Author

![image](https://github.com/Khmelov/DC2024-01-27/assets/108403999/d8ace542-3b32-4073-b06b-b9c06982f20c)

**Comment by Khmelov** [comment]
Да, спс, я это уже сделал. При обновлении будет ок.
